{
  "timestamp": "2025-10-25T14:14:37.478681Z",
  "latencies": {
    "predictive": {
      "status": "down",
      "error": "HTTPConnectionPool(host='localhost', port=8010): Max retries exceeded with url: /healthz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000287FB2ABA10>, 'Connection to localhost timed out. (connect timeout=2)'))"
    },
    "analytics": {
      "status": "down",
      "error": "HTTPConnectionPool(host='localhost', port=8020): Max retries exceeded with url: /healthz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000287FB28FB10>, 'Connection to localhost timed out. (connect timeout=2)'))"
    }
  }
}